#!/usr/bin/env python
import os
import sys

# 导入SConstruct环境
env = SConscript("godot-cpp/SConstruct")


#------------可设置参数----------------------------------
# 设置库的名称，默认为lib
lib_name = "lib"
# 额外的库文件，默认为空
external_lib = []
# 第三方库路径
external_lib_path = []



#-------------初始化，配置-------------------------
#------------------------------------------------
libpath = "./demo/bin/{}/{}{}{}".format(env["platform"], lib_name, env['suffix'], env['SHLIBSUFFIX'])

sources = []      # Cpp文件位置
CPPPATH_temp = [] # 头文件位置

current_path = os.getcwd() # 当前目录位置
build_dir = current_path + "/build/" # 构建目录

# 检测目录
if not os.path.exists(build_dir):
    os.makedirs(build_dir)

# 构建目录配置
env["OBJPREFIX"] = build_dir

# if env["CXX"] == "cl":  # MSVC
env.Replace(CXXFLAGS="/std:c++20")


# 输出目录
# print("xxxx:" + env["ENV"]["INCLUDE"])
print("Building Info ...<!!>")
print(" - C++ version:" + env["CXXFLAGS"])
# print(" - C++ version:" + env["CXXVERSION"])
print(" - Current dir:" + current_path)
print(" - Build dir:"+ build_dir)

#------------准备函数-------------------------------
#-------------------------------------------------
# 遍历目录和文件
def recursive_listdir():
    paths = os.walk(r'src')
    # path：路径
    # dir_list：目录
    # file_lst：文件
    for path, dir_list, file_lst in paths:

        for dir_name in file_lst:
            file_extension = os.path.splitext(dir_name) # 获取文件后缀
           
            if file_extension[1] == ".cpp":
                sources.append(Glob(os.path.join(path, dir_name)))

def recursive_head_files():
    paths = os.walk(r'include')
    # path：路径
    # dir_list：目录
    # file_lst：文件
    for path, dir_list, file_lst in paths:
        # .h文件目录
        CPPPATH_temp.append(path) # 添加目录

#--------------------------------------------------#
#--------------------------------------------------#
# 添加第三方库路径
if external_lib_path:
    print(" - Add external lib path")
    # 输出额外库名称
    for f in external_lib_path:
        print("   +", f)

    # 额外添加的库路径
    env.Append(LIBPATH=external_lib_path)


# 添加库位置
if external_lib:
    print(" - Add external lib")
    # 输出额外库名称
    for f in external_lib:
        print("   +", f)

    # 额外添加的库
    env.Append(LIBS=external_lib)  

#- 添加.cpp .h文件
recursive_listdir() # 添加.cpp文件
recursive_head_files() # 添加.h文件

# 添加register_type文件
sources.append(Glob(os.path.join(current_path, "register_types.cpp")))
CPPPATH_temp.append(current_path) 

# 添加.cpp、.h文件夹路径
# CPPPATH只能是目录，不能包含文件
env.Append(CPPPATH = CPPPATH_temp)
sharedlib = env.SharedLibrary(libpath, sources)

# 设置scons默认编译的文件
env.Default(sharedlib)
