#!/usr/bin/env python
import os
import sys

# 导入SConstruct环境
env = SConscript("godot-cpp/SConstruct")


## 库相关设置
lib_name = "auto_start_manager" # 库的名称
project_name = "demo"   # 项目名称，每一个项目都是不同名称

## 系统库设置
## 一些程序需要windows库的支持
# user32.lib	用户界面相关 (窗口、消息、注册表等)
# shell32.lib	Shell相关功能 (文件操作、系统对话框等)
# advapi32.lib	高级API (注册表、服务、安全等)
# kernel32.lib	核心系统功能 (进程、内存、文件等)
sys_external_lib = ["user32", "shell32", "advapi32"]

## 第三方库路径，
## 一些特别的库，需要在编译的时候添加
external_lib_path = []



#-------------初始化，配置-------------------------
#------------------------------------------------
libpath = "./{}/bin/{}/{}{}{}".format(project_name, env["platform"], lib_name, env['suffix'], env['SHLIBSUFFIX'])

sources = []      # Cpp文件位置
CPPPATH_temp = [] # 头文件位置

current_path = os.getcwd() # 当前目录位置
build_dir = current_path + "/build/" # 构建目录

# 检测目录
if not os.path.exists(build_dir):
    os.makedirs(build_dir)

# 构建目录配置
env["OBJPREFIX"] = build_dir

# 输出目录
print(" ")
print("Building Info ...<!!>")
print(" - Lib Name: " + lib_name)
print(" - Current dir: " + current_path)
print(" - Build dir: "+ build_dir)
print(" ")

#------------准备函数-------------------------------
#-------------------------------------------------
# 遍历目录和文件
def recursive_listdir():
    paths = os.walk(r'src')
    # path：路径
    # dir_list：目录
    # file_lst：文件
    for path, dir_list, file_lst in paths:

        for dir_name in file_lst:
            file_extension = os.path.splitext(dir_name) # 获取文件后缀
           
            if file_extension[1] == ".cpp":
                sources.append(Glob(os.path.join(path, dir_name)))


def recursive_head_files():
    paths = os.walk(r'include')
    # path：路径
    # dir_list：目录
    # file_lst：文件
    for path, dir_list, file_lst in paths:
        # .h文件目录
        CPPPATH_temp.append(path) # 添加目录

#--------------------------------------------------#
#--------------------------------------------------#
# 添加第三方库路径
if external_lib_path:
    print(" - Add external lib path")
    # 输出额外库名称
    for f in external_lib_path:
        print("   +", f)

    # 额外添加的库路径
    env.Append(LIBPATH=external_lib_path)
    print(" ")


# 添加库位置
if sys_external_lib:
    print(" - Add external lib")
    # 输出额外库名称
    for f in sys_external_lib:
        print("   +", f)

    # 额外添加的库
    env.Append(LIBS=sys_external_lib)  

print(" ")

#- 添加.cpp .h文件
recursive_listdir() # 添加.cpp文件
recursive_head_files() # 添加.h文件

# 添加register_type文件
sources.append(Glob(os.path.join(current_path, "register_types.cpp")))
CPPPATH_temp.append(current_path) 

# 添加.cpp、.h文件夹路径
# CPPPATH只能是目录，不能包含文件
env.Append(CPPPATH = CPPPATH_temp)
sharedlib = env.SharedLibrary(libpath, sources)

# 设置scons默认编译的文件
env.Default(sharedlib)
