#!/usr/bin/env python
import os
import sys

# 导入SConstruct环境
env = SConscript("godot-cpp/SConstruct")


#------------可设置参数----------------------------------
## 库相关设置
## lib_name: 库的名称
## project_name: 项目名称（默认为demo），确定位置
lib_name = "keyboard_listener"
project_name = "demo"


## 系统库设置
## 一些程序需要windows库的支持
sys_external_lib = ["user32"]
# sys_external_lib = ["user32", "shell32"]


## 第三方库路径，
## 一些特别的库，需要在编译的时候添加
external_lib_path = []



#-------------初始化，配置-------------------------
#------------------------------------------------
libpath = "./{}/bin/{}/{}{}{}".format(project_name, env["platform"], lib_name, env['suffix'], env['SHLIBSUFFIX'])

sources = []      # Cpp文件位置
CPPPATH_temp = [] # 头文件位置

current_path = os.getcwd() # 当前目录位置
build_dir = current_path + "/build/" # 构建目录

# 检测目录
if not os.path.exists(build_dir):
    os.makedirs(build_dir)

# 构建目录配置
env["OBJPREFIX"] = build_dir

# 输出目录
print(" ")
print("Building Info ...<!!>")
print(" - Lib Name: " + lib_name)
print(" - Current dir: " + current_path)
print(" - Build dir: "+ build_dir)
print(" ")

#------------准备函数-------------------------------
#-------------------------------------------------
# 遍历目录和文件
#! 这个方法会自动遍历子目录
def recursive_listdir(d_n):
    paths = os.walk(d_n)
    # path：路径
    # dir_list：目录
    # file_lst：文件
    for path, dir_list, file_lst in paths:

        for dir_name in file_lst:
            file_extension = os.path.splitext(dir_name) # 获取文件后缀
           
            if file_extension[1] == ".cpp":
                sources.append(Glob(os.path.join(path, dir_name)))


#! 这个方法会自动遍历子目录
def recursive_head_files(d_n):
    paths = os.walk(d_n)
    # path：路径
    # dir_list：目录
    # file_lst：文件
    for path, dir_list, file_lst in paths:
        # .h文件目录
        # print(path)
        CPPPATH_temp.append(path) # 添加目录

#--------------------------------------------------#
#--------------------------------------------------#
# 添加第三方库路径
if external_lib_path:
    print("Add External Lib Path")
    # 输出额外库名称
    for f in external_lib_path:
        print("   +", f)

    # 额外添加的库路径
    env.Append(LIBPATH=external_lib_path)
    print(" ")


# 添加库位置
if sys_external_lib:
    print("Add System Lib Name")
    # 输出额外库名称
    for f in sys_external_lib:
        print("   +", f)

    # 额外添加的库
    env.Append(LIBS=sys_external_lib)  
    print(" ")


#- 添加.cpp .h文件
recursive_listdir(r'src') # 添加src目录, 及其子目录下的.cpp文件
recursive_listdir(r'configs') # 添加configs目录，及其子目录下的.cpp文件

recursive_head_files(r'include') # 添加include目录，及其子目录下的.h文件
recursive_head_files(r'configs') # 添加configs目录，及其子目录下的.h文件

# 添加register_type文件的头文件与源文件
# sources.append(Glob(os.path.join(current_path, "register_types.cpp")))
# CPPPATH_temp.append(current_path)

print("Include dir Info")
print(" - " + str(CPPPATH_temp))
print(" ")
print(" ")


# 向环境中添加头文件路径与源代码路径
# CPPPATH只能是目录，不能包含文件
env.Append(CPPPATH = CPPPATH_temp)
sharedlib = env.SharedLibrary(libpath, sources)

# 设置scons默认编译的文件
env.Default(sharedlib)
